### ISSUE TITLE
When the code will be public?

### ISSUE THREAD

**Issue by 7Dreamzan** [zengwang430521/TCFormer#1]
I'm interested in your task. Could you please public your code? Thanks.

**Comment by Mrkkew** [comment]
I'm also interested in your work, and when will the code be released?

**Comment by zengwang430521** [comment]
The code is waiting for the approval process to complete and I will update the code as soon as possible.

**Comment by namepllet** [comment]
Do you plan to release codes for 2D Wholebody keypoints estimation and 3D mesh estimation ?

**Comment by zengwang430521** [comment]
Yes. Because I have refactored my code, I need to retrain the model. I will update these codes after the checkpoint is ready.
