### ISSUE TITLE
Params和Flops是怎么算的

### ISSUE THREAD

**Issue by 60wanjinbing** [zengwang430521/TCFormer#10]
![image](https://user-images.githubusercontent.com/3793990/208022561-dec38063-0dba-4e0c-a51a-c3165dc531a6.png)
请问下，你这个Params和Flops是怎么算的，我按照你论文中的ImageNet算的不是这个值
我代码中的输入值是 data = torch.randn(128, 3, 224, 224) ，这个算出来的结果是，Params: 19.240M  FLOPS: 327.397G

**Comment by jin-s13** [comment]
see https://github.com/zengwang430521/TCFormer/blob/master/tcformer_module/custom_flops_counter.py

**Comment by jin-s13** [comment]
and  https://github.com/zengwang430521/TCFormer/blob/master/classification/get_flops.py
