### ISSUE TITLE
关于代码细节的问题

### ISSUE THREAD

**Issue by xiaobaitu123344** [zengwang430521/TCFormer#12]
idx_token_new = index_points(idx_cluster[..., None], idx_token).squeeze(-1)
    weight_t = index_points(norm_weight, idx_token)
    agg_weight_new = agg_weight * weight_t
    agg_weight_new / agg_weight_new.max(dim=1, keepdim=True)[0]

最后一行应该是/=吧

**Comment by xiaobaitu123344** [comment]
https://github.com/zengwang430521/TCFormer/blob/master/tcformer_module/tcformer_utils.py
487行

**Comment by imabackstabber** [comment]
i agree

**Comment by imabackstabber** [comment]
could some answer this? @zengwang430521 @jin-s13

**Comment by imabackstabber** [comment]
> @xiaobaitu123344 @imabackstabber
> 
> Hi, sorry for the late reply.
> 
> You are right, it's a mistake. Thank you for your care. But fortunately, this mistake does not influence the model.
> 
> This line aims to normalize the aggregation weight to make sure it will not be too large. But with this mistake, normalization is not executed. Fortunately, what matters is the relative ratio between the aggeragtion weights. So this mistake does not change the following process.
> 
> You can correct this line or just remove this line.
> 
> I may correct this mistake later.
> 
> Thanks again.

Thanks!
And i want to ask about your experiment setting.
In paper you said, "The model is trained with 8 GPUs with a batch size of 32 in each GPU for 80 epochs." I test on my node, which has a 24gb gpu, with batchsize 32 input. And it seems drain all the memory up.
I wonder how much gpu memory you got?

**Comment by zengwang430521** [comment]
@imabackstabber 
I have 32GB memory on each gpu.
