### ISSUE TITLE
[BUG] error when using gpu

### ISSUE THREAD

**Issue by imabackstabber** [zengwang430521/TCFormer#14]
Hi @jin-s13 @zengwang430521 , I write a script which call tcformer to forward a batched input:
```python
import torch
from tcformer_module.tcformer import tcformer

if __name__ == '__main__':
    device = torch.device("cuda")
    model = tcformer().to(device)
    fake = torch.randn((32,3,224,224)).to(device)
    output = model(fake)

```
it works fine on cpu, but when I'm using gpu, it somehow errors and gives feedback below:
```bash
Traceback (most recent call last):                                                                                                              
  File "tcformer_module/test.py", line 8, in <module>                                                                                           
    output = model(fake)                                                                                                                        
  File "/home/path/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl                             
    return forward_call(*input, **kwargs)                                                                                                       
  File "/home/path/git_repo/TCFormer/tcformer_module/tcformer.py", line 146, in forward                                                    
    x = self.forward_features(x)                                                                                                                
  File "/home/path/git_repo/TCFormer/tcformer_module/tcformer.py", line 133, in forward_features                                           
    token_dict = ctm(token_dict)  # down sample                                                                                                 
  File "/home/path/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl                             
    return forward_call(*input, **kwargs)                                                                                                       
  File "/home/path/git_repo/TCFormer/tcformer_module/tcformer_layers.py", line 442, in forward                                             
    down_dict = merge_tokens(token_dict, idx_cluster, cluster_num, token_weight)                                                                
  File "/home/path/git_repo/TCFormer/tcformer_module/tcformer_utils.py", line 488, in merge_tokens                                         
    agg_weight_new = agg_weight * weight_t                                                                                                      
RuntimeError: CUDA error: an illegal memory access was encountered                                                                              
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.                          
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```
At first I thought it was because gpu memory depletion, because it works fine on gpu when the batchsize is small enough(such as 2,4,8,etc).but it turns out that maybe batchsize doesn't matter, when i using **16 batchsize**, i set a breakpoint in function and it turns out memory usage is merely 5927MiB.So where is the fault?
torch version:1.13.0+cu117
cuda version:11.1

**Comment by zengwang430521** [comment]
@imabackstabber 
Hi, I failed to reproduce this error. This error seems to be caused by a wrong token index. Have you modified the codes?

**Comment by imabackstabber** [comment]
> @imabackstabber Hi, I failed to reproduce this error. This error seems to be caused by a wrong token index (negative index or too large). Have you modified the codes?

nope, I haven't modify any code. It seems that it happens in `merge_tokens  ` function, I'm not sure whether it's my CUDA version problem.

**Comment by zengwang430521** [comment]
Hi, I do not know the reason of this bug, as I failed to reproduce it. Maybe you can print the `idx_cluster` to see whether there is any problem. Or you can try another cuda version, I use CUDA 10.1 in previous experiments.

**Comment by imabackstabber** [comment]
ok, i might try your cuda version. thanks.

**Comment by yuhanyao** [comment]
i also face this problem and i find that it is caused by `dist_nearest, index_nearest = torch.topk(dist_matrix, k=k, dim=-1, largest=False)` in function `cluster_dpc_knn`. thus, i cannot print `idx_cluster` to check why the problem occurs for it happens before the variable is assigned. 
i use CIFAR for training without modifying any code. make the batch size small works(eg. batch size=16), but i wonder could i use bigger batch to train my model.
could you tell me if this problem has been solved? @imabackstabber .
