### ISSUE TITLE
pose依赖版本问题

### ISSUE THREAD

**Issue by Jasookii** [zengwang430521/TCFormer#15]
您好，首先非常感谢您优秀的工作。我想复线关于pose的部分，但有关mm的依赖问题难以解决，因此翔想问下pose相关代码的mmpose、mmcv、mmengine的版本，期待您的回复。

**Comment by jin-s13** [comment]
https://github.com/open-mmlab/mmpose/blob/2c4a60e357c7f68f3388f0fc4ddcb404674b81ae/docs/zh_cn/notes/changelog.md?plain=1#L31

TCFormer is supported in mmpose v0.28.0
