### ISSUE TITLE
About the visualization

### ISSUE THREAD

**Issue by Mrkkew** [zengwang430521/TCFormer#3]
I'm wondering how the visualization in your paper is done, and could you provide the code of the visualization?

**Comment by zengwang430521** [comment]
You can use the function vis_tokens
https://github.com/zengwang430521/TCFormer/blob/d777f368a4c054e925b9491776a905814870441e/tcformer_module/tcformer_utils.py#L470

**Comment by Mrkkew** [comment]
OK, thanks a lot!

**Comment by lllrj** [comment]
想知道这个在mmpose里怎么还原成原图呢？我按照mean和std将函数输出的vis_img进行了
```
vis_img = vis_img.cpu()
mean = np.array([0.485, 0.456, 0.406])
std = np.array([0.229, 0.224, 0.225])
mean = torch.as_tensor(mean, dtype=float, device='cpu')
std = torch.as_tensor(std, dtype=float, device='cpu')
if mean.ndim == 1:
    mean = mean.view(-1, 1, 1)
if std.ndim == 1:
    std = std.view(-1, 1, 1)

vis_img = vis_img.mul_(std).add_(mean)
vis_img = vis_img.mul_(255)
vis_img = vis_img.squeeze(0).cpu().numpy().transpose((1, 2, 0))
plt.imshow(vis_img)
plt.savefig()
````
但是输出不大对

**Comment by lllrj** [comment]
> 想知道这个在mmpose0.x里怎么还原成原图呢？我按照意思和std将函数输出的vis_img进行还原了，下段代码在fcformer里for循环中写的。我的意思是像论文中那样将各阶段性关键情况显现出来。
> 
> ```
> # 加入位置
>         for i in range(1, self.num_stages):
>             # print('stage = ', i)
>             ctm = getattr(self, f'ctm{i}')
>             ups = getattr(self, f'ups{i}')
>             block = getattr(self, f'block{i + 1}')
>             norm = getattr(self, f'norm{i + 1}')
>             # print('pre x.shape = ',token_dict['x'].shape)
>             token_dict = ctm(token_dict)  # down sample
>             vis_img = vis_tokens(img, token_dict[0])
> ```
> 
> ```
> # 具体添加代码
> vis_img = vis_tokens(img, token_dict[0])
> 
> import matplotlib.pyplot as plt
> import numpy as np
> 
> vis_img = vis_img.squeeze(0).cpu()
> mean = np.array([0.485, 0.456, 0.406])
> std = np.array([0.229, 0.224, 0.225])
> mean = torch.as_tensor(mean, dtype=float, device='cpu')
> std = torch.as_tensor(std, dtype=float, device='cpu')
> if mean.ndim == 1:
>     mean = mean.view(-1, 1, 1)
> if std.ndim == 1:
>     std = std.view(-1, 1, 1)
> 
> vis_img.mul_(std).add_(mean)
> vis_img.mul_(255)
> vis_img = vis_img.numpy().transpose((1, 2, 0))
> plt.imshow(vis_img)
> plt.savefig()
> ```
> 
> 但输出不太对

直接调出原图传入才行了
