### ISSUE TITLE
pretrained models.

### ISSUE THREAD

**Issue by mls1999725** [zengwang430521/TCFormer#7]
Hi, I noticed that training 2D pose estimation requires a pretrained model (pretrained='pretrained/tcformer-4e1adbf1_20220421.pth'). I would like to ask how to obtain this model? 
Looking forward to your reply !

**Comment by jin-s13** [comment]
<img width="752" alt="截屏2022-07-06 上午9 47 30" src="https://user-images.githubusercontent.com/11788150/177449949-566078cf-9b2e-44bd-b52a-131ad770a1c7.png">

These are imagenet_pretrained models. Please check the links here.
